//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _specs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_specs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseJson_1Alpha_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseJson_1Alpha_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseJson_1Alpha4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseJson_1Alpha4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseJson_1AlphaX_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseJson_1AlphaX_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseJson_1AlphaX4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseJson_1AlphaX4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseJson_Set_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseJson_Set_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseProtobuf_1Alpha_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseProtobuf_1Alpha_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseProtobuf_1Alpha4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseProtobuf_1Alpha4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseProtobuf_1AlphaX_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseProtobuf_1AlphaX_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseProtobuf_1AlphaX4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseProtobuf_1AlphaX4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HBaseProtobuf_Set_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseProtobuf_Set_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CellSet&gt;
        ///	&lt;Row key=&quot;MQ==&quot;&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///	&lt;/Row&gt;
        ///&lt;/CellSet&gt;.
        /// </summary>
        internal static string HBaseXml_1Alpha_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseXml_1Alpha_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CellSet&gt;
        ///	&lt;Row key=&quot;MQ==&quot;&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6&quot; timestamp=&quot;4&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///	&lt;/Row&gt;
        ///&lt;/CellSet&gt;.
        /// </summary>
        internal static string HBaseXml_1Alpha4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseXml_1Alpha4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CellSet&gt;
        ///	&lt;Row key=&quot;MQ==&quot;&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6eA==&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///	&lt;/Row&gt;
        ///&lt;/CellSet&gt;.
        /// </summary>
        internal static string HBaseXml_1AlphaX_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseXml_1AlphaX_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CellSet&gt;
        ///	&lt;Row key=&quot;MQ==&quot;&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6eA==&quot; timestamp=&quot;4&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///	&lt;/Row&gt;
        ///&lt;/CellSet&gt;.
        /// </summary>
        internal static string HBaseXml_1AlphaX4_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseXml_1AlphaX4_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found
        ///.
        /// </summary>
        internal static string HBaseXml_FindCellsEmptyResponse {
            get {
                return ResourceManager.GetString("HBaseXml_FindCellsEmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CellSet&gt;
        ///	&lt;Row key=&quot;MQ==&quot;&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6eA==&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6&quot; timestamp=&quot;4&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///		&lt;Cell column=&quot;YWxwaGE6eA==&quot; timestamp=&quot;4&quot;&gt;aGVsbG8gd29ybGQ=&lt;/Cell&gt;
        ///	&lt;/Row&gt;
        ///&lt;/CellSet&gt;.
        /// </summary>
        internal static string HBaseXml_Set_HelloWorld {
            get {
                return ResourceManager.GetString("HBaseXml_Set_HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///
        ///&lt;TableSchema name=&quot;jb-test&quot; IS_META=&quot;false&quot; IS_ROOT=&quot;false&quot;&gt;
        ///	&lt;ColumnSchema name=&quot;d&quot; BLOCKSIZE=&quot;65536&quot; BLOOMFILTER=&quot;NONE&quot; MIN_VERSIONS=&quot;0&quot; KEEP_DELETED_CELLS=&quot;false&quot;
        ///	              ENCODE_ON_DISK=&quot;true&quot; BLOCKCACHE=&quot;true&quot; COMPRESSION=&quot;NONE&quot; VERSIONS=&quot;3&quot; REPLICATION_SCOPE=&quot;0&quot;
        ///	              TTL=&quot;2147483647&quot; DATA_BLOCK_ENCODING=&quot;NONE&quot; IN_MEMORY=&quot;false&quot; /&gt;
        ///&lt;/TableSchema&gt;.
        /// </summary>
        internal static string HBaseXml_TableSchema1 {
            get {
                return ResourceManager.GetString("HBaseXml_TableSchema1", resourceCulture);
            }
        }
    }
}
