// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18213
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace _specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HBase Stargate Resource Builder")]
    public partial class HBaseStargateResourceBuilderFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HBaseStargateResourceBuilder.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HBase Stargate Resource Builder", "In order to avoid using the wrong resource URI for a particular operation\r\nAs a S" +
                    "targate Client consumer\r\nI want to be sure that the resource URI is correct for " +
                    "every situation", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I have everything I need to test a resource builder in isolation, assuming a fals" +
                    "e-row-key of \"newRow\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cell or Row query")]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "4", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "4", "5", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForCellOrRowQueryNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "", "", "test/*", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "", "5", "test/*/*/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "4", "", "test/*", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "4", "5", "test/*/*/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "", "", "test/*", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "", "5", "test/*/*/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "4", "", "test/*", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "4", "5", "test/*/*/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "", "", "test/*/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "", "5", "test/*/alpha/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "4", "", "test/*/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "4", "5", "test/*/alpha/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "", "", "test/*/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "", "5", "test/*/alpha:x/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "4", "", "test/*/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "4", "5", "test/*/alpha:x/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "", "5", "test/1/*/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "4", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "4", "5", "test/1/*/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "", "5", "test/1/*/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "4", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "4", "5", "test/1/*/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "", "", "test/1/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "", "5", "test/1/alpha/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "4", "", "test/1/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "4", "5", "test/1/alpha/4,5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "", "", "test/1/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "", "5", "test/1/alpha:x/5", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "4", "", "test/1/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "4", "5", "test/1/alpha:x/4,5", "should", "", "", null)]
        public virtual void CellOrRowQuery(string table, string row, string column, string qualifier, string begin, string end, string resource, string shouldOrShouldNot, string exception, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cell or Row query", exampleTags);
#line 9
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 10
 testRunner.Given(string.Format("I have a cell query consisting of a {0}, a {1}, a {2}, a {3}, a {4} timestamp, an" +
                        "d a {5} timestamp", table, row, column, qualifier, begin, end), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.When("I build a resource name for Cell or Row queries using my identifier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then(string.Format("the resulting resource name should match the expected {0}", resource), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.And(string.Format("the operation {0} have succeeded", shouldOrShouldNot), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And(string.Format("if there was an exception, it should have been the expected {0} type", exception), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("if there was an exception, it should have had the expected exception {0}", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Single value storage")]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForSingleValueAccessNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "", "test/1/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "4", "test/1/alpha/4", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "", "test/1/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "4", "test/1/alpha:x/4", "should", "", "", null)]
        public virtual void SingleValueStorage(string table, string row, string column, string qualifier, string timestamp, string resource, string shouldOrShouldNot, string exception, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single value storage", exampleTags);
#line 83
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 84
 testRunner.Given(string.Format("I have an identifier consisting of a {0}, a {1}, a {2}, a {3}, and a {4}", table, row, column, qualifier, timestamp), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.When("I build a resource name for storing single values using my identifier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.Then(string.Format("the resulting resource name should match the expected {0}", resource), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
 testRunner.And(string.Format("the operation {0} have succeeded", shouldOrShouldNot), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And(string.Format("if there was an exception, it should have been the expected {0} type", exception), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And(string.Format("if there was an exception, it should have had the expected exception {0}", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Write multiple values")]
        [NUnit.Framework.TestCaseAttribute("", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForBatchInsertNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "test/newRow", "should", "", "", null)]
        public virtual void WriteMultipleValues(string table, string resource, string shouldOrShouldNot, string exception, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Write multiple values", exampleTags);
#line 125
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 126
 testRunner.Given(string.Format("I have an identifier consisting of a {0}", table), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
 testRunner.When("I build a resource name for storing multiple values using my identifier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.Then(string.Format("the resulting resource name should match the expected {0}", resource), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
 testRunner.And(string.Format("the operation {0} have succeeded", shouldOrShouldNot), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And(string.Format("if there was an exception, it should have been the expected {0} type", exception), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.And(string.Format("if there was an exception, it should have had the expected exception {0}", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete an item")]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("", "1", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "", "alpha", "x", "4", "", "should not", "ArgumentException", "ResourceBuilder_MinimumForDeleteItemNotMet", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "", "4", "test/1/*/4", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "", "test/1", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "", "x", "4", "test/1/*/4", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "", "test/1/alpha", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "", "4", "test/1/alpha/4", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "", "test/1/alpha:x", "should", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("test", "1", "alpha", "x", "4", "test/1/alpha:x/4", "should", "", "", null)]
        public virtual void DeleteAnItem(string table, string row, string column, string qualifier, string timestamp, string resource, string shouldOrShouldNot, string exception, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete an item", exampleTags);
#line 137
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 138
 testRunner.Given(string.Format("I have an identifier consisting of a {0}, a {1}, a {2}, a {3}, and a {4}", table, row, column, qualifier, timestamp), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.When("I build a resource name for deleting items using my identifier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 140
 testRunner.Then(string.Format("the resulting resource name should match the expected {0}", resource), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
 testRunner.And(string.Format("the operation {0} have succeeded", shouldOrShouldNot), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And(string.Format("if there was an exception, it should have been the expected {0} type", exception), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.And(string.Format("if there was an exception, it should have had the expected exception {0}", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
