// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18213
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace _specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Identifier Matching")]
    public partial class IdentifierMatchingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "IdentifierMatching.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Identifier Matching", "In order to determine whether two identifiers are similar\r\nAs an hbase-client con" +
                    "sumer\r\nI want to compare full identifiers with partial ones and get predictable " +
                    "results", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successful Match; Table Only")]
        public virtual void SuccessfulMatchTableOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful Match; Table Only", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table1.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 7
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "table"});
            table2.AddRow(new string[] {
                        "test"});
#line 10
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table2, "And ");
#line 13
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("the identifier match should have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed Match; Table Only")]
        public virtual void FailedMatchTableOnly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed Match; Table Only", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table3.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 17
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "table"});
            table4.AddRow(new string[] {
                        "foo"});
#line 20
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table4, "And ");
#line 23
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("the identifier match should not have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successful Match; Table and Row")]
        public virtual void SuccessfulMatchTableAndRow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful Match; Table and Row", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table5.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 27
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row"});
            table6.AddRow(new string[] {
                        "test",
                        "row1"});
#line 30
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table6, "And ");
#line 33
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.Then("the identifier match should have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed Match; Table and Row")]
        public virtual void FailedMatchTableAndRow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed Match; Table and Row", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table7.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 37
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table7, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row"});
            table8.AddRow(new string[] {
                        "test",
                        "foo"});
#line 40
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table8, "And ");
#line 43
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.Then("the identifier match should not have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successful Match; Table, Row, and Column")]
        public virtual void SuccessfulMatchTableRowAndColumn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful Match; Table, Row, and Column", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table9.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 47
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column"});
            table10.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1"});
#line 50
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table10, "And ");
#line 53
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("the identifier match should have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed Match; Table, Row, and Column")]
        public virtual void FailedMatchTableRowAndColumn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed Match; Table, Row, and Column", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table11.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 57
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column"});
            table12.AddRow(new string[] {
                        "test",
                        "row1",
                        "foo"});
#line 60
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table12, "And ");
#line 63
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.Then("the identifier match should not have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successful Match; Table, Row, Column, and Qualifier")]
        public virtual void SuccessfulMatchTableRowColumnAndQualifier()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful Match; Table, Row, Column, and Qualifier", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table13.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 67
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table13, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier"});
            table14.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1"});
#line 70
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table14, "And ");
#line 73
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.Then("the identifier match should have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed Match; Table, Row, Column, and Qualifier")]
        public virtual void FailedMatchTableRowColumnAndQualifier()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed Match; Table, Row, Column, and Qualifier", ((string[])(null)));
#line 76
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table15.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 77
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table15, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier"});
            table16.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "foo"});
#line 80
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table16, "And ");
#line 83
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.Then("the identifier match should not have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successful Match; Table, Row, Column, Qualifier, and Timestamp")]
        public virtual void SuccessfulMatchTableRowColumnQualifierAndTimestamp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful Match; Table, Row, Column, Qualifier, and Timestamp", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table17.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 87
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table17, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table18.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 90
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table18, "And ");
#line 93
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.Then("the identifier match should have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed Match; Table, Row, Column, Qualifier, and Timestamp")]
        public virtual void FailedMatchTableRowColumnQualifierAndTimestamp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed Match; Table, Row, Column, Qualifier, and Timestamp", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table19.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "100"});
#line 97
 testRunner.Given("I have an identifier consisting of the following values:", ((string)(null)), table19, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "table",
                        "row",
                        "column",
                        "qualifier",
                        "timestamp"});
            table20.AddRow(new string[] {
                        "test",
                        "row1",
                        "column1",
                        "qualifier1",
                        "200"});
#line 100
 testRunner.And("I have a second identifier consisting of the following values:", ((string)(null)), table20, "And ");
#line 103
 testRunner.When("I match the second identifier to the first one", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.Then("the identifier match should not have succeeded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
